// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlKhMCNm6Jf-5u7t2da4KtapLheVsA3Y',
    appId: '1:196427380925:web:0702ff16a100beace5dfd4',
    messagingSenderId: '196427380925',
    projectId: 'push-notifications-8d319',
    authDomain: 'push-notifications-8d319.firebaseapp.com',
    storageBucket: 'push-notifications-8d319.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCFBvUPiKwRvgqytRjvHNgIHoZJUIseH4',
    appId: '1:196427380925:android:9c469781ebfdb64fe5dfd4',
    messagingSenderId: '196427380925',
    projectId: 'push-notifications-8d319',
    storageBucket: 'push-notifications-8d319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_F0V-mOVxT8X_FlQ-Y9etFPD95Bh6Lec',
    appId: '1:196427380925:ios:4043583a640e9887e5dfd4',
    messagingSenderId: '196427380925',
    projectId: 'push-notifications-8d319',
    storageBucket: 'push-notifications-8d319.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_F0V-mOVxT8X_FlQ-Y9etFPD95Bh6Lec',
    appId: '1:196427380925:ios:4043583a640e9887e5dfd4',
    messagingSenderId: '196427380925',
    projectId: 'push-notifications-8d319',
    storageBucket: 'push-notifications-8d319.firebasestorage.app',
    iosBundleId: 'com.example.flutterPushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQlKhMCNm6Jf-5u7t2da4KtapLheVsA3Y',
    appId: '1:196427380925:web:2d952738b683be35e5dfd4',
    messagingSenderId: '196427380925',
    projectId: 'push-notifications-8d319',
    authDomain: 'push-notifications-8d319.firebaseapp.com',
    storageBucket: 'push-notifications-8d319.firebasestorage.app',
  );
}
